/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cp2project;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ahmet
 */
public class EditUserScreen extends javax.swing.JFrame {

    /**
     * Creates new form EditUserScreen
     */
    public EditUserScreen() {
        initComponents();
        //This codes takes values on user that created with login codes and writes this values to relevant textfields.
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        textfield_name.setText(Homescreen.user.getName());
        textfield_surname.setText(Homescreen.user.getSurname());
        textfield_birthdate.setText(Homescreen.user.getBirth_date());
        textfield_email.setText(Homescreen.user.getMail());
        textfield_password.setText(Homescreen.user.getPassword());
        if (Homescreen.user.getGender() == 0) {
            radioutton_male.setSelected(true);
        } else {
            radiobutton_female.setSelected(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        name_label = new javax.swing.JLabel();
        textfield_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textfield_surname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textfield_birthdate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        radioutton_male = new javax.swing.JRadioButton();
        radiobutton_female = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        textfield_email = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textfield_password = new javax.swing.JTextField();
        button_update = new javax.swing.JButton();
        button_deleteuser = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edit User Information");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        name_label.setText("Name");

        jLabel2.setText("Surname");

        jLabel3.setText("Birth Date(yyyy-mm-dd)");

        jLabel4.setText("Gender");

        buttonGroup1.add(radioutton_male);
        radioutton_male.setText("Male");

        buttonGroup1.add(radiobutton_female);
        radiobutton_female.setText("Female");

        jLabel5.setText("E-Mail");

        jLabel6.setText("Password");

        button_update.setText("Update");
        button_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_updateActionPerformed(evt);
            }
        });

        button_deleteuser.setText("Delete User");
        button_deleteuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_deleteuserActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Name", "Surname", "Birth Date", "Gender", "E-mail", "Password", "Role" }));

        jButton1.setText("Show");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(button_update, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(button_deleteuser, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(141, 141, 141)
                                    .addComponent(name_label))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton1)
                                    .addGap(102, 102, 102)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(radioutton_male)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(radiobutton_female))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(textfield_email, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(textfield_surname, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(textfield_name, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(textfield_birthdate, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(6, 6, 6)
                                                    .addComponent(jLabel3)))
                                            .addComponent(textfield_password, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(239, 239, 239)
                            .addComponent(jLabel2))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_label)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfield_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addComponent(textfield_surname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textfield_birthdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioutton_male)
                    .addComponent(radiobutton_female))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(7, 7, 7)
                .addComponent(textfield_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textfield_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(button_deleteuser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_update, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_updateActionPerformed
        //Asks user to if user is sure or not with confirm dialog.
        int result = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to update the user?", "Confirmation", JOptionPane.YES_NO_OPTION);

        try {
            //User is sure. Takes the values on textfields.
            if (result == JOptionPane.YES_OPTION) {
                String name = textfield_name.getText();
                String surname = textfield_surname.getText();
                String birthdate = textfield_birthdate.getText();
                String email = textfield_email.getText();
                String password = textfield_password.getText();
                int gender;
                if (radioutton_male.isSelected()) {
                    gender = 0;
                } else {
                    gender = 1;
                }
                //The user is created depending on whether it is admin user or regular user.
                User user_updated;
                if (Homescreen.user instanceof AdminUser) {
                    user_updated = new AdminUser(Homescreen.user.getId(), name, surname, birthdate, gender, email, password);
                    user_updated = (AdminUser) user_updated;
                } else {
                    user_updated = new RegularUser(Homescreen.user.getId(), name, surname, birthdate, gender, email, password);
                    user_updated = (RegularUser) user_updated;
                }

                boolean truth_value = DatabaseManagement.UpdateUser(user_updated);
                //Creates an option pane to inform if it is updated or not
                if (truth_value) {
                    JOptionPane.showMessageDialog(rootPane, "Succesfuly updated");
                    Homescreen.user = user_updated;
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Cannot updated");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }

    }//GEN-LAST:event_button_updateActionPerformed

    private void button_deleteuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_deleteuserActionPerformed
        //Asks user to if user is sure or not with confirm dialog.
        int result = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to delete the user?", "Confirmation", JOptionPane.YES_NO_OPTION);

        //User is sure. Takes the values on textfields.
        try {
            if (result == JOptionPane.YES_OPTION) {
                String name = textfield_name.getText();
                String surname = textfield_surname.getText();
                String birthdate = textfield_birthdate.getText();
                String email = textfield_email.getText();
                String password = textfield_password.getText();
                int gender;
                if (radioutton_male.isSelected()) {
                    gender = 0;
                } else {
                    gender = 1;
                }
                //User deleting after taking values on textfields.
                boolean truth_value = DatabaseManagement.DeleteUser(Homescreen.user);
                //Informs user if deleting process is successful or not. Deleting user that assigned on login process and creating a new Homescreen.
                if (truth_value) {
                    JOptionPane.showMessageDialog(rootPane, "Successfuly deleted");
                    Homescreen.user = null;
                    setVisible(false);
                    Homescreen form = new Homescreen();
                    form.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Cannot deleted");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }


    }//GEN-LAST:event_button_deleteuserActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            if(jComboBox1.getSelectedIndex()==0){
        JOptionPane.showMessageDialog(rootPane, "Orginal is: "+Homescreen.user.getName());
        }else if(jComboBox1.getSelectedIndex()==1){
        JOptionPane.showMessageDialog(rootPane, "Orginal is: "+Homescreen.user.getSurname());
        }else if(jComboBox1.getSelectedIndex()==2){
        JOptionPane.showMessageDialog(rootPane, "Orginal is: "+Homescreen.user.getBirth_date());
        }else if(jComboBox1.getSelectedIndex()==3){
        JOptionPane.showMessageDialog(rootPane, "Orginal is: "+Homescreen.user.getGender());
        }else if(jComboBox1.getSelectedIndex()==4){
        JOptionPane.showMessageDialog(rootPane, "Orginal is: "+Homescreen.user.getMail());
        }else if(jComboBox1.getSelectedIndex()==5){
        JOptionPane.showMessageDialog(rootPane, "Orginal is: "+Homescreen.user.getPassword());
        }else if(jComboBox1.getSelectedIndex()==6){
        JOptionPane.showMessageDialog(rootPane, "Orginal is: "+Homescreen.user.ReturnValues());
        }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton button_deleteuser;
    private javax.swing.JButton button_update;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel name_label;
    private javax.swing.JRadioButton radiobutton_female;
    private javax.swing.JRadioButton radioutton_male;
    private javax.swing.JTextField textfield_birthdate;
    private javax.swing.JTextField textfield_email;
    private javax.swing.JTextField textfield_name;
    private javax.swing.JTextField textfield_password;
    private javax.swing.JTextField textfield_surname;
    // End of variables declaration//GEN-END:variables
}
