/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cp2project;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author ahmet
 */
public class SignUpScreen extends javax.swing.JFrame {

    /**
     * Creates new form SignUpScreen
     */
    public SignUpScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        name_label = new javax.swing.JLabel();
        textfield_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textfield_surname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textfield_birthdate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textfield_email = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textfield_password = new javax.swing.JTextField();
        radioutton_male = new javax.swing.JRadioButton();
        radiobutton_female = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sign Up");

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        name_label.setText("Name");

        jLabel2.setText("Surname");

        jLabel3.setText("Birth Date(yyyy-mm-dd)");

        jLabel4.setText("Gender");

        jLabel5.setText("E-Mail");

        jLabel6.setText("Password");

        buttonGroup1.add(radioutton_male);
        radioutton_male.setSelected(true);
        radioutton_male.setText("Male");

        buttonGroup1.add(radiobutton_female);
        radiobutton_female.setText("Female");

        jButton1.setText("Sign Up");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(textfield_name)
                        .addComponent(textfield_birthdate)
                        .addComponent(textfield_surname)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(radioutton_male)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(radiobutton_female))
                        .addComponent(textfield_password)
                        .addComponent(textfield_email)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(name_label))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel3)))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(name_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textfield_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textfield_surname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textfield_birthdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioutton_male)
                    .addComponent(radiobutton_female))
                .addGap(7, 7, 7)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textfield_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textfield_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        /*
        Takes values on every textfield and radiobutton. Controls all values with regex patterns and returns a boolean value accordingly to this
         */

        String name = textfield_name.getText();
        boolean a = false;
        Pattern pattern = Pattern.compile("^[A-Z][a-zA-Z]*$");
        Matcher matcher = pattern.matcher(name);
        boolean matchFound = matcher.matches();
        if (matchFound) {
            a = true;
        } else {
            JOptionPane.showMessageDialog(rootPane, "Name must start with capital letter and cannot include anything except letters");
        }

        String surname = textfield_surname.getText();
        boolean b = false;
        Pattern pattern2 = Pattern.compile("^[A-Z][a-zA-Z]*$");
        Matcher matcher2 = pattern2.matcher(surname);
        boolean matchFound2 = matcher2.matches();
        if (matchFound2) {
            b = true;
        } else {
            JOptionPane.showMessageDialog(rootPane, "Surname must start with capital letter and cannot include anything except letters");
        }

        String birth_date = textfield_birthdate.getText();
        boolean c = false;
        Pattern pattern3 = Pattern.compile("^(19|20)\\d\\d-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$");
        Matcher matcher3 = pattern3.matcher(birth_date);
        boolean matchFound3 = matcher3.matches();
        if (matchFound3) {
            c = true;
        } else {
            JOptionPane.showMessageDialog(rootPane, "Birth date must be like this: 2000-09-27");
        }
        var gender_value = 0;
        if (radioutton_male.isSelected()) {
            gender_value = 0;
        } else {
            gender_value = 1;
        }

        String email = textfield_email.getText();
        boolean d = false;
        Pattern pattern4 = Pattern.compile("^[a-zA-Z0-9._%+-]+@(gmail\\.com|hotmail\\.com)$");
        Matcher matcher4 = pattern4.matcher(email);
        boolean matchFound4 = matcher4.matches();
        if (matchFound4) {
            d = true;
        } else {
            JOptionPane.showMessageDialog(rootPane, "You can only enter 'gmail' or 'hotmail'");
        }

        String password = textfield_password.getText();
        boolean e = false;
        Pattern pattern5 = Pattern.compile("^(?=.*[A-Z])(?=.*[!@#$%^&*(),.?\":{}|<>]).+$");
        Matcher matcher5 = pattern5.matcher(password);
        boolean matchFound5 = matcher5.matches();
        if (matchFound5) {
            e = true;
        } else {
            JOptionPane.showMessageDialog(rootPane, "Password must include at least one special character and one capital letter");
        }

        //If all values matched with regex, then new user will be created and inform the user about it.
        if (a == true && b == true && c == true && d == true && e == true) {
            boolean truth_value = DatabaseManagement.AddUser(name, surname, birth_date, gender_value, email, password);
            if (truth_value) {
                JOptionPane.showMessageDialog(rootPane, "Succesfully signed up");
                //It will retirn the first frame and close this frame
                Homescreen form = new Homescreen();
                form.setVisible(true);
                setVisible(false);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel name_label;
    private javax.swing.JRadioButton radiobutton_female;
    private javax.swing.JRadioButton radioutton_male;
    private javax.swing.JTextField textfield_birthdate;
    private javax.swing.JTextField textfield_email;
    private javax.swing.JTextField textfield_name;
    private javax.swing.JTextField textfield_password;
    private javax.swing.JTextField textfield_surname;
    // End of variables declaration//GEN-END:variables
}
